version: "3.8"
services:
  # ALBとcloudfrontの代替
  mock-lb:
    build: ./mock-lb
    container_name: rs-mock-lb
    image: rs-mock-lb
    depends_on:
      - web
    environment:
      TARGET_SERVER: web
      STATIC_BUCKET: https://hogehoge.com
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./logs/mock-lb:/var/log/nginx
  web:
    build: ./web
    container_name: rs-web
    image: rs-web
    depends_on:
      - app
    environment:
      BACK_END_HOST: app
    volumes:
      - ./logs/web:/var/log/nginx
  app:
    build: ./app
    container_name: rs-app
    image: rs-app
    depends_on:
      mock-redis:
        condition: service_started
      mock-db:
        condition: service_healthy
    environment:
      RDB_RW_ENDPOINT: mock-db
      RDB_RO_ENDPOINT: mock-db
      RDB_USER: root
      RDB_PASSWORD: SamplePW
      RDB_NAME: review_stock
#    ports:
#      - 8080:8080
    volumes:
      - ./back-src/build/libs/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./logs/app:/usr/local/tomcat/logs
  mock-db:
    build: ./mock-db
    container_name: rs-mock-db
    image: rs-mock-db
    environment:
      MYSQL_ROOT_PASSWORD: SamplePW
      MYSQL_DATABASE: review_stock
#    ports:
#      - 3306:3306
    volumes:
      - ./mock-db/mysql_init:/docker-entrypoint-initdb.d
      - ./logs/mock-db:/var/log/mysql
    # dbの起動確認
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
  mock-redis:
    build: ./mock-redis
    image: rs-mock-redis
    container_name: rs-mock-redis
#    ports:
#      - 6379:6379
