spring:
  datasource:
    url: jdbc:mysql:replication://${RDB_RW_ENDPOINT}:3306,${RDB_RO_ENDPOINT}:3306/${DB_NAME}?serverTimezone=JST
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: 0
